import { Router } from "express";
import appNotificationRoutes from "../modules/appNotifications/appNotification.routes.js";
import authRoutes from "../modules/auth/auth.routes.js";
import branchRoutes from "../modules/branch/branch.routes.js";
import staffRoutes from "../modules/staff/staff.routes.js";
import memberRoutes from "../modules/member/member.routes.js";
import planRoutes from "../modules/plans/plan.routes.js";
import publicAttendanceRoutes from "../modules/attendance/publicAttendance.routes.js";
import classRoutes from "../modules/classes/class.routes.js";
import paymentRoutes from "../modules/payments/payment.routes.js";
import publicPaymentRoutes from "../modules/payments/publicPayment.routes.js";
import dashboardRoutes from "../modules/dashboard/dashboard.routes.js";

const router = Router();

// test route
router.get("/ping", (req, res) => {
  res.json({ status: "ok" });
});

router.use("/auth", authRoutes);
router.use("/branches", branchRoutes);
router.use("/staff", staffRoutes);
router.use("/members", memberRoutes);
router.use("/plans", planRoutes);
router.use("/attendance/public", publicAttendanceRoutes);
router.use("/class", classRoutes);
router.use("/payments", paymentRoutes);
router.use("/payments/public", publicPaymentRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/memberattendence", memberAttendenceRoutes);
router.use("/alerts", alertRoutes);
router.use("/expenses", expenseRoutes);
router.use("/finance", financeRoutes);
router.use("/diet", dietRoutes);
router.use("/workout", workoutRoutes);
router.use("/notif", notifRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/purchases", purchaseRoutes);
router.use("/MemberPlan", MemberPlan);
router.use("/member-plan-assignments", memberPlanAssignmentRoutes);
router.use("/sessions", sessionRoutes);
router.use("/salaries", SalaryRoutes);
router.use("/housekeepingtask", houseKeepingRoutes);
router.use("/staff-attendance", staffAttendanceRoutes);
router.use("/housekeepingdashboard", housekeepingDashboardRoutes);
router.use("/generaltrainer", generaltrainerRoutes);
router.use("/shift", shiftRoutes);
router.use("/personal-trainer-dashboard", personalTrainerDashboardRoutes);
// router.use("/housekeeping-attendance", housekeepingAttendance);
router.use("/member-dashboard", memberDeshboardRoutes);
router.use("/admin-staff-attendance", adminStaffAttendanceRoutes);
router.use("/member-self", memberSelfRoutes);
router.use("/reports", reportsRoutes);
router.use("/booking", bookingRoutes);
router.use("/adminSettings", adminSettingsRoutes);
router.use("/leads", leadRoutes);
router.use("/health", healthRoutes);
router.use("/v1/health", healthRoutes);
router.use("/subadmins", subadminRoutes);
router.use("/global-settings", globalSettingRoutes);
router.use("/v1/assessments", assessmentRoutes);
router.use("/v1/leaderboard", leaderboardRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/v1/bodybuilding", bodybuildingRoutes);
router.use("/receptionist-dashboard", receptionistDashboardRoutes);
router.use("/v1/equipment", equipmentRoutes);
router.use("/v1/automation", automationRoutes);
router.use("/v1/credits", creditsRoutes);
router.use("/app-notifications", appNotificationRoutes);
router.use("/v1/message-templates", messageTemplateRoutes);
router.use("/integrations", integrationsRoutes);

export default router;
